### ISSUE TITLE
对话脚本自动补全yaml语法错误，少空格

### ISSUE THREAD

**Issue by k-jiang** [EverMCServer/BQTools#16]
![tab自动补全错误-少空格](https://user-images.githubusercontent.com/6910542/77844361-caf2b600-71d8-11ea-8a25-fd1d90cdd7d1.png)
如图，手动输入元素并按tab后，补全内容少空格，不符合yaml语法规定。

**Comment by peaceshi** [comment]
无法复现. 补全内容应与双引号无关.

补全只会替换引号内内容. 即 `${2:false}`

https://github.com/EverMCServer/BQTools/blob/5cecf17f2d217555c9361c399e5265ad38a6100c/Snippets/BetonQuest.code-snippets#L24

**Comment by peaceshi** [comment]
此问题可能是schema自动补全功能造成的.
https://github.com/EverMCServer/BQTools/blob/5cecf17f2d217555c9361c399e5265ad38a6100c/schema/conversations-schema.json#L17-L19
