### ISSUE TITLE
对话脚本 增加extend(s)支持

### ISSUE THREAD

**Issue by k-jiang** [EverMCServer/BQTools#18]
![WEE_W0YG43TTR}5T3~A_1DO](https://user-images.githubusercontent.com/6910542/77844697-48b7c100-71db-11ea-84c9-514f65a6ac7b.png)
![image](https://user-images.githubusercontent.com/6910542/77844698-49e8ee00-71db-11ea-98cb-a250dfb95f2b.png)
相当于“引用”，详见wiki：https://wiki.evermc.com/%E6%8F%92%E4%BB%B6%E6%89%8B%E5%86%8C/betonquest/%E5%9F%BA%E6%9C%AC%E6%A6%82%E5%BF%B5#%E5%AF%B9%E8%AF%9D%E7%BB%A7%E6%89%BF_extends

**Comment by peaceshi** [comment]
Official wiki:

https://github.com/Co0sh/BetonQuest/wiki/Reference#conversations

> `text` defines what will display on screen. If you don't want to set any events/conditions/pointers to the option, just skip them. **Only `text` is always required.**

So, `text` is always required or not ?

**Comment by k-jiang** [comment]
Not strictly required.

If options is pointed by an "extends", it is not consider a standalone "option". So it doesn't required the "text" component as well.

Consider it more like an abstract object: Multiple options could include/share some extra elements from another option, like events, conditions, pointers to the other options, even extra part of text, etc.

Notice that elements in "extends" is pointed to the same direction of conversation flow, i.e, NPC_options points to NPC_options, player_options points to player_options.
