### ISSUE TITLE
修复所有schema不能正确验证default目录下测试文件格式的错误

### ISSUE THREAD

**Issue by peaceshi** [EverMCServer/BQTools#3]
根据 https://github.com/EverMCServer/BQTools/issues/1#issue-573392354 进行测试并修复所有错误.

@xz-dev

**Comment by xz-dev** [comment]
已修复所有可见错误 https://github.com/EverMCServer/BQTools/commit/60ed0025934ba9645dac5d332441c1e54f9054cc
